---
title: "stat230hw3file"
author: "EricBourgain"
date: "2/22/2022"
output: html_document
---
I recently rebuilt my computer and have had issues uploading to my github account so I've included the functions in this folder.

Problem 1 


```{r}
#install.packages("../",repos=NULL,type="source")
devtools::install_github('https://github.com/echang992000/stats230local',force=TRUE)
library(stats230local)
library(tidyverse)
library(bench)

# import data
SAheart <- read_csv("https://hastie.su.domains/ElemStatLearn/datasets/SAheart.data")
SAheart$famhist=as.numeric(as.factor(SAheart$famhist))

# scale and extract x,y matrices for regression. use chd as response variable according to docs
df=scale(SAheart)
x=as.matrix(df[,2:10])
y=as.matrix(SAheart[,11])

# define sigmoid function
sigmoid=function(theta,x){
  return((1+exp(-x%*%theta))**-1)
}

# gradient method
out1=logreg(x,y,1)
theta1=out1[[1]]
error1=out1[[2]]
lik1=out1[[3]]
print(error1) # width/2 of the confidence interval

# newton method
out2=logreg(x,y,2)
theta2=out2[[1]]
error2=out2[[2]]
lik2=out2[[3]]
print(error2)

# likelihood comparison
plot(lik1[1:40])
title(main="likelihood comparison for logistic regression",xlab="iterations",ylab="likelihood")
points(lik2[1:40],col=2)
legend("bottomright",legend=c("gradient","newton"),col=c(1,2),lty=1,pch=20)

# benchmarking
b1=bench::mark(logreg(x,y,1),min_iterations=50)
b2=bench::mark(logreg(x,y,2),min_iterations=50)
b3=b1 %>% add_row(b2)
plot(b3)

```
Clear difference in performance, with the gradient descent much faster (Hessian calculation and inversion is time consuming). However, newton's method is quadratic and converges much more quickly





Problem 2

```{r}
n=c(6,4,55,35)
pa=0.3
pb=0.3
po=0.4
p=em(n,pa,pb,po)

plot(p[1,],type="l",xlim=c(1,11),ylim=c(0,1))
title(main="EM Alg for Alle Frequency Probabilities in ABO blood type")
lines(p[2,],col=2)
lines(p[3,],col=3)
legend("topright",legend=c("pA","pB","pO"),col=c(1,2,3),lty=1,pch=20)


```



Problem 3
```{r}
p=matrix(c(0.98,.05,.02,.95),ncol=2) # prob matrix
e=matrix(rep(c(1/6,1/10),6),ncol=6) # emissions matrix
e[2,3]=1/2

v=matrix(c(1/2,1/2),ncol=1)# initial 
x=sample(c(1,2),size=1,prob=v)
y=sample(c(1:6),size=1,prob=e[1,])

# simulate for 100 rolls
for (k in 1:100){
  x0=x[k]
  x=rbind(x,sample(c(1,2),size=1,prob=p[x0,]))
  y=rbind(y,sample(c(1:6),size=1,prob=e[x[k+1],]))
}

plot(x)
title("Hidden States for pair of Dice, 1 is fair, 2 is loaded",xlab="iterations",ylab="state")

plot(y)
title("Observed States for pair of Dice",xlab="iterations",ylab="face of dice")


# backward
b=matrix(0,2,101)
b[,dim(b)[2]]=1
for (t in 100:1){
  for (i in 1:2){
    for (j in 1:2){
      b[i,t]=b[i,t]+p[i,j]*e[1,y[t+1]]*b[j,t+1]
    }
  }
}
b[,1]=sum(v*e[,y[1]]*b[,2])

# forward
a=matrix(0,2,101)
a[,1]=v*e[,y[1]]
for (t in 1:100){
  for (i in 1:2){
    for (j in 1:2){
      a[i,t+1]=a[i,t+1]+e[i,y[t+1]]*a[j,t]*p[i,j]
    }
  }
}


# marginals
m=matrix(0,2,101)
for (t in 1:101){
  for (i in 1:2){
    m[i,t]=a[i,t]*b[i,t]/(t(a[,t])%*%b[,t])
  }
}

plot(x,ylim=c(0,2))
title(main="Fair dice: Marginal vs True",xlab="iterations",ylab="probability/state")
points(m[1,],col=2)
points(m[2,],col=3)
legend("topleft",legend=c("true","marginal for fair","marginal for loaded"),col=c(1,2,3),lty=1,pch=20)


p0=matrix(c(0.5,.5,.5,.5),ncol=2)
e0=matrix(rep(c(1/6,1/6),6),ncol=6)
v0=matrix(c(1/2,1/2),ncol=1)
out3=bw(p0,e0,v0,0.01)
print(p0)
print(e0)
print(v0)

```
